
server:
  port: 8088
#  tomcat:
#    accept-count: 0
#    accesslog:
#      file-date-format: yyyy-MM-dd
#      enabled: true
#      prefix: pxf_access_log
#      suffix: .log
#    basedir:
#    max-connections: 0
#    max-threads: 0
#    max-http-header-size: 0
#    max-http-post-size: 0


spring:
  datasource:
    url: jdbc:mysql://10.53.156.240:3306/loanpublic?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: dev
    password: ****
#    url: jdbc:mysql://127.0.0.1:3306/loanpublic?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
#    username: root
#    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 0
    jedis:
      pool:
        max-wait: -1
        max-active: 8
        max-idle: 8
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: admin
#    password: 123456
  servlet:
    multipart:
      max-file-size: 10485760
      max-request-size: 10485760
      file-size-threshold: 0
  mail:
    host: smtp.qq.com
    username: 475054216@qq.com
    password: ddidgwfdweqobjdc
    default-encoding: UTF-8

# 与mybatis整合
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  row-bounds-with-count: true